// Major French cities with their France Travail department codes.
// The dept code is used for the `departement` param in the FT API.
export const VILLES = [
  { label: "Paris",            dept: "75" },
  { label: "Lyon",             dept: "69" },
  { label: "Marseille",        dept: "13" },
  { label: "Toulouse",         dept: "31" },
  { label: "Nice",             dept: "06" },
  { label: "Nantes",           dept: "44" },
  { label: "Montpellier",      dept: "34" },
  { label: "Strasbourg",       dept: "67" },
  { label: "Bordeaux",         dept: "33" },
  { label: "Lille",            dept: "59" },
  { label: "Rennes",           dept: "35" },
  { label: "Reims",            dept: "51" },
  { label: "Saint-Étienne",    dept: "42" },
  { label: "Toulon",           dept: "83" },
  { label: "Le Havre",         dept: "76" },
  { label: "Grenoble",         dept: "38" },
  { label: "Dijon",            dept: "21" },
  { label: "Angers",           dept: "49" },
  { label: "Nîmes",            dept: "30" },
  { label: "Villeurbanne",     dept: "69" },
  { label: "Clermont-Ferrand", dept: "63" },
  { label: "Aix-en-Provence",  dept: "13" },
  { label: "Brest",            dept: "29" },
  { label: "Tours",            dept: "37" },
  { label: "Amiens",           dept: "80" },
  { label: "Limoges",          dept: "87" },
  { label: "Rouen",            dept: "76" },
  { label: "Metz",             dept: "57" },
  { label: "Nancy",            dept: "54" },
  { label: "Perpignan",        dept: "66" },
  { label: "Caen",             dept: "14" },
  { label: "Orléans",          dept: "45" },
  { label: "Mulhouse",         dept: "68" },
  { label: "Besançon",         dept: "25" },
  { label: "Valenciennes",     dept: "59" },
  { label: "Pau",              dept: "64" },
  { label: "Avignon",          dept: "84" },
  { label: "Dunkerque",        dept: "59" },
  { label: "Lorient",          dept: "56" },
  { label: "Poitiers",         dept: "86" },
  { label: "La Rochelle",      dept: "17" },
  { label: "Roubaix",          dept: "59" },
  { label: "Tourcoing",        dept: "59" },
  { label: "Montreuil",        dept: "93" },
  { label: "Saint-Denis",      dept: "93" },
  { label: "Argenteuil",       dept: "95" },
  { label: "Colmar",           dept: "68" },
  { label: "Bayonne",          dept: "64" },
  { label: "Troyes",           dept: "10" },
];

export function getDeptFromVille(villeLabel) {
  const found = VILLES.find((v) => v.label.toLowerCase() === villeLabel?.toLowerCase());
  return found?.dept ?? null;
}
